name: CI

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

  # deploy-github-pages:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: pnpm/action-setup@v2
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 16.x
  #         cache: pnpm

  #     - name: Install
  #       run: pnpm install

  #     - name: Build
  #       run: pnpm run build

  #     - name: Deploy Github Pages 🚀
  #       uses: JamesIves/github-pages-deploy-action@v4
  #       with:
  #         folder: dist

  deploy-serve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy to serve 🚀
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: -rlgoDzvc -i --delete
          SOURCE: dist/
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: root
          TARGET: /var/www/cn.wiidede.space
          EXCLUDE: '/dist/, /node_modules/'
